import pandas as pd
import numpy as np
from pathlib import Path

df = pd.read_csv('results/csv/youth_mar_baseline.csv')
print('=' * 70)
print('Youth Experiment - Baseline Results Summary')
print('=' * 70)
print(f'Total rows: {len(df)}')
print(f"Configurations: {df.groupby(['batch_id', 'model', 'missing_rate']).ngroups}")
print()
print('Methods:', df['method'].unique())
print('Models:', df['model'].unique())
print('Batches:', df['batch_id'].unique())
print('MRs:', sorted(df['missing_rate'].unique()))
print()
print('-' * 70)
print('Performance by Missing Rate (Baseline only)')
print('-' * 70)
summary = df.groupby('missing_rate')['test_mae'].agg(['mean', 'std', 'count'])
print(summary.to_string())
print()
print('-' * 70)
print('Performance by Model (Baseline only)')
print('-' * 70)
model_summary = df.groupby('model')['test_mae'].agg(['mean', 'std'])
print(model_summary.to_string())
